/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Marina
 */
public class ADDUSER extends javax.swing.JFrame {

    /**
     * Creates new form ADDUSER
     */
    public ADDUSER() {
        initComponents();
    }
    
     public ADDUSER(String us){
         initComponents();
         user.setText(us);
     }
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        degree = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        aadhar = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        join = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        valid1 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        id = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        locality = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        validd = new javax.swing.JLabel();
        valid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1020, 100, 330, 80);

        jLabel10.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Qualification");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 830, 330, 80);

        department.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        department.setForeground(new java.awt.Color(0, 102, 102));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel1.add(department);
        department.setBounds(1400, 106, 300, 64);

        jLabel17.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1060, 830, 330, 80);

        jLabel21.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gender");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(170, 420, 240, 70);

        jLabel18.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Aadhar no.");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(170, 720, 320, 80);

        jLabel16.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mobile No.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(170, 510, 330, 80);

        degree.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        degree.setForeground(new java.awt.Color(0, 102, 102));
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });
        jPanel1.add(degree);
        degree.setBounds(540, 840, 300, 70);

        jLabel19.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Email-ID");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(170, 620, 320, 80);

        mobile.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        mobile.setForeground(new java.awt.Color(0, 102, 102));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        jPanel1.add(mobile);
        mobile.setBounds(590, 520, 260, 70);

        email.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        email.setForeground(new java.awt.Color(0, 102, 102));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(540, 620, 300, 64);

        jLabel15.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Joining Date");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1060, 410, 330, 90);

        aadhar.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        aadhar.setForeground(new java.awt.Color(0, 102, 102));
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        aadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aadharKeyTyped(evt);
            }
        });
        jPanel1.add(aadhar);
        aadhar.setBounds(540, 730, 300, 60);

        post.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        post.setForeground(new java.awt.Color(0, 102, 102));
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        jPanel1.add(post);
        post.setBounds(1400, 220, 300, 60);

        password.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        password.setForeground(new java.awt.Color(0, 102, 102));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(1400, 846, 300, 64);

        jLabel23.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Salary");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1060, 320, 280, 58);

        dob.setForeground(new java.awt.Color(0, 102, 102));
        dob.setFont(new java.awt.Font("FZYaoTi", 1, 20)); // NOI18N
        dob.setMaxSelectableDate(new java.util.Date(946668671000L));
        dob.setMinSelectableDate(new java.util.Date(-16129000L));
        jPanel1.add(dob);
        dob.setBounds(540, 320, 300, 60);

        jLabel20.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(170, 210, 250, 80);

        salary.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        salary.setForeground(new java.awt.Color(0, 102, 102));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel1.add(salary);
        salary.setBounds(1450, 320, 250, 70);

        jLabel24.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("D.O.B");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(170, 320, 240, 70);

        female.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(female);
        female.setFont(new java.awt.Font("FZYaoTi", 0, 30)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        jPanel1.add(female);
        female.setBounds(700, 430, 140, 60);

        join.setForeground(new java.awt.Color(0, 102, 102));
        join.setFont(new java.awt.Font("FZYaoTi", 1, 20)); // NOI18N
        join.setMaxSelectableDate(new java.util.Date(1638300671000L));
        join.setMinSelectableDate(new java.util.Date(946668671000L));
        jPanel1.add(join);
        join.setBounds(1400, 420, 300, 70);

        jButton1.setBackground(new java.awt.Color(230, 230, 230));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-100.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 880, 130, 110);

        valid1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        valid1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(valid1);
        valid1.setBounds(1400, 910, 300, 20);

        male.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(male);
        male.setFont(new java.awt.Font("FZYaoTi", 0, 30)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        jPanel1.add(male);
        male.setBounds(550, 430, 140, 60);

        id.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        id.setForeground(new java.awt.Color(0, 102, 102));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(540, 110, 300, 60);

        state.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        state.setForeground(new java.awt.Color(0, 102, 102));
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        jPanel1.add(state);
        state.setBounds(1400, 740, 300, 60);

        jLabel22.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Employee ID");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(170, 100, 330, 80);

        city.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        city.setForeground(new java.awt.Color(0, 102, 102));
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel1.add(city);
        city.setBounds(1400, 630, 300, 60);

        jLabel13.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Job Post");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1060, 210, 290, 80);

        jLabel3.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("+91");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 520, 60, 70);

        locality.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        locality.setForeground(new java.awt.Color(0, 102, 102));
        locality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localityActionPerformed(evt);
            }
        });
        jPanel1.add(locality);
        locality.setBounds(1400, 526, 300, 64);

        jLabel14.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Locality");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1060, 510, 270, 80);

        jLabel4.setFont(new java.awt.Font("FZYaoTi", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rs.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1390, 320, 62, 70);

        validd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        validd.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(validd);
        validd.setBounds(540, 800, 300, 20);

        valid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 255, 255));
        valid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validKeyTyped(evt);
            }
        });
        jPanel1.add(valid);
        valid.setBounds(541, 586, 300, 20);

        jLabel12.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("State");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1060, 720, 300, 80);

        jLabel11.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("City");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1060, 620, 300, 70);

        name.setFont(new java.awt.Font("FZYaoTi", 1, 50)); // NOI18N
        name.setForeground(new java.awt.Color(0, 102, 102));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(540, 210, 300, 64);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-login-100.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1750, 870, 150, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 70, 1910, 930);

        jLabel7.setFont(new java.awt.Font("FZYaoTi", 0, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("ADD EMPLOYEE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(810, 0, 470, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1910, 1010);
        jPanel1.add(user);
        user.setBounds(210, 50, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement mystmt=null;
         
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
           String q="insert into employee(Employee_id, Employee_password, Employee_name, Gender, Mobile, Email_ID, Qualification, Salary, Locality, City, State, Date_of_birth, Department, Aadhar_no, Job, Joiningdate, Hobby)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; 
           mystmt = con.prepareStatement(q);
                int a=Integer.parseInt(mobile.getText());
                int b=Integer.parseInt(aadhar.getText());
                if(a==10&&b==12){
                    mystmt.setString(1, id.getText());
                     mystmt.setString(2, password.getText());
                    mystmt.setString(3, name.getText());
          
                    if(male.isSelected()){
                     String m="Male";   
                       mystmt.setString(4, m);
                    }
                     if(female.isSelected()){
                     String m="Female";       
                       mystmt.setString(4, m);
                    }
                    
                    String str=mobile.getText();
                    if(str.length()==10){
                    mystmt.setString(5, mobile.getText());}
                    else{
                     JOptionPane.showMessageDialog(this,"Enter Valid Moble no.","INVALID",JOptionPane.ERROR_MESSAGE);
                     mobile.setText("");
                    }
                    
                       String st=email.getText();
                    if(st.length()==12){
                    mystmt.setString(6, email.getText());
                    }
                     else{
                     JOptionPane.showMessageDialog(this,"Enter Valid Aadhar no.","INVALID",JOptionPane.ERROR_MESSAGE);
                     email.setText("");
                    }
                     mystmt.setString(7, degree.getText());
                      mystmt.setString(8, salary.getText());
                      mystmt.setString(9, locality.getText());
                      mystmt.setString(10, city.getText());
                      mystmt.setString(11, state.getText());
                      
                      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                      String date=sdf.format(dob.getDate());
                      mystmt.setString(12, date);
                      
                      mystmt.setString(13, department.getText());
                     mystmt.setString(14, aadhar.getText());
                     mystmt.setString(15, post.getText());
                  
                     
                       sdf = new SimpleDateFormat("yyyy-MM-dd");
                      String dat=sdf.format(join.getDate());
                      mystmt.setString(16, dat);
                         mystmt.setString(17, "music");
                      mystmt.executeUpdate();
                      
            String us=user.getText();
             int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Add new Employee record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
                JOptionPane.showMessageDialog(this,"Employee Details added Successfully","Sucessfull",JOptionPane.INFORMATION_MESSAGE);
                 String u=user.getText();
                 new ADMINHOME(u).setVisible(true);
        } 
        }else{
                JOptionPane.showMessageDialog(this,"Please Enter a valid Mobile no. and Aadhar no.","Anticipated",JOptionPane.WARNING_MESSAGE);
                }       
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
              JOptionPane.showMessageDialog(this,"Please Enter a valid Data Without Letting Fields Empty","Anticipated",JOptionPane.WARNING_MESSAGE);
           
        }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void localityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localityActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
     
    }//GEN-LAST:event_mobileActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
    
    }//GEN-LAST:event_aadharActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
      
    }//GEN-LAST:event_passwordActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String us = user.getText();
        new ADMINHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
       
        try{
        
        int a=Integer.parseInt(mobile.getText()); 
        valid.setText("");
    }
    catch(NumberFormatException el){
        valid.setText("Enter Numeric Values");
    
    }       
    }//GEN-LAST:event_mobileKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
  
    }//GEN-LAST:event_passwordKeyTyped

    private void validKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_validKeyTyped

    private void aadharKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aadharKeyTyped
      try{
        int a=Integer.parseInt(aadhar.getText()); 
        validd.setText("");
    }
    catch(NumberFormatException el){
        validd.setText("Enter Numeric Values");
    
    }       
    }//GEN-LAST:event_aadharKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDUSER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField city;
    private javax.swing.JTextField degree;
    private javax.swing.JTextField department;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser join;
    private javax.swing.JTextField locality;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField post;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField state;
    private javax.swing.JLabel user;
    private javax.swing.JLabel valid;
    private javax.swing.JLabel valid1;
    private javax.swing.JLabel validd;
    // End of variables declaration//GEN-END:variables
}
