/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author josep
 */
public class EMPLOYEESETTINGS extends javax.swing.JFrame {

    /**
     * Creates new form EMPLOYEESETTINGS
     */
    public EMPLOYEESETTINGS() {
        initComponents();
    }

     public EMPLOYEESETTINGS(String us){
         initComponents();
         user.setText(us);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        old = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(null);

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-login-100 (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(1470, 730, 150, 120);

        jLabel10.setFont(new java.awt.Font("FZYaoTi", 0, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("New Password");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(1130, 520, 380, 70);

        jLabel9.setFont(new java.awt.Font("FZYaoTi", 0, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Old Password");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(1130, 270, 380, 60);

        jLabel4.setFont(new java.awt.Font("FZYaoTi", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("CHANGE PASSWORD");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(940, 10, 640, 110);

        jLabel6.setFont(new java.awt.Font("FZYaoTi", 0, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PERSONAL SETTINGS");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(40, 10, 640, 110);

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.add(jButton9);
        jButton9.setBounds(930, 120, 620, 9);

        old.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        old.setForeground(new java.awt.Color(180, 180, 180));
        old.setText("password");
        old.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldMouseClicked(evt);
            }
        });
        old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldActionPerformed(evt);
            }
        });
        jPanel5.add(old);
        old.setBounds(1130, 330, 430, 90);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jButton8);
        jButton8.setBounds(40, 120, 620, 9);

        jButton1.setBackground(new java.awt.Color(200, 200, 200));
        jButton1.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("MODIFY SECURITY ANSWER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(80, 360, 560, 80);

        jButton2.setBackground(new java.awt.Color(200, 200, 200));
        jButton2.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("CHANGE EMAIL-ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(80, 490, 560, 80);

        jButton7.setBackground(new java.awt.Color(200, 200, 200));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(80, 870, 560, 110);

        jButton10.setBackground(new java.awt.Color(0, 153, 153));
        jButton10.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("CHANGE PASSWORD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(80, 230, 560, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-key-100.png"))); // NOI18N
        jPanel5.add(jLabel8);
        jLabel8.setBounds(910, 570, 100, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halfblue.jpg"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(-100, 0, 820, 1000);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(720, 930, 570, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-lock-104.png"))); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(890, 310, 130, 120);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(790, 900, 380, 40);

        newpassword.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        newpassword.setForeground(new java.awt.Color(180, 180, 180));
        newpassword.setText("password");
        newpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newnewpasswordMouseClicked(evt);
            }
        });
        newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnewpasswordActionPerformed(evt);
            }
        });
        jPanel5.add(newpassword);
        newpassword.setBounds(1130, 580, 430, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel5.add(jLabel1);
        jLabel1.setBounds(720, 0, 1240, 1000);

        user.setText("jLabel9");
        jPanel5.add(user);
        user.setBounds(10, 20, 41, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        PreparedStatement mystmt=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "Select * from employee where Employee_name=? and Employee_password=?";

            mystmt = con.prepareStatement(sql);
            mystmt.setString(1, user.getText());
            mystmt.setString(2, old.getText());
            ResultSet rs = mystmt.executeQuery();
            String us=user.getText();

            if(rs.next()){
                String s=newpassword.getText();
                if(s.length()<10&&s.length()>5){
                String query="UPDATE employee SET Employee_password=? WHERE Employee_name=?";
                mystmt= con.prepareStatement(query);
                mystmt.setString(1, newpassword.getText());
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Password updation complete","Successful",JOptionPane.INFORMATION_MESSAGE);
                new ADMINHOME(us).setVisible(true);
                dispose();

                }
                else{
                  JOptionPane.showMessageDialog(this,"Entered Password should be in range 5-10 characters","Anticipated",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Entered Password is wrong","Anticipated",JOptionPane.ERROR_MESSAGE);
                old.setText("");
                newpassword.setText("");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void oldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldMouseClicked
        old.setText("");
        old.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_oldMouseClicked

    private void oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String us = user.getText();
        new EMPLOYEESECURITYANSWER(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String us = user.getText();
        new EMPLOYEEEMAIL(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new EMPLOYEEHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void newnewpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newnewpasswordMouseClicked

        newpassword.setText("");
        newpassword.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_newnewpasswordMouseClicked

    private void newnewpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnewpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newnewpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESETTINGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESETTINGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESETTINGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESETTINGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLOYEESETTINGS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPasswordField old;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
