/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author josep
 */
public class EMPLOYEEMANAGEMENT extends javax.swing.JFrame {

    /**
     * Creates new form EMPLOYEEMANAGEMENT
     */
    public EMPLOYEEMANAGEMENT() {
        initComponents();
    }
     public EMPLOYEEMANAGEMENT(String us){
         initComponents();
         user.setText(us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        locality = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        degree = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        join = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        employee = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(null);

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-login-100 (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(1590, 780, 140, 110);

        jLabel25.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Department");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(1370, 170, 220, 70);

        jLabel22.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Gender");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(760, 430, 160, 60);

        jLabel20.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("City");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(1370, 590, 110, 60);

        jLabel24.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("State");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(1370, 670, 200, 60);

        jLabel21.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Salary");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(1370, 340, 120, 46);

        jLabel26.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Job Post");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(1370, 250, 170, 60);

        jLabel23.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Qualification");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(760, 750, 230, 50);

        department.setBackground(new java.awt.Color(0, 102, 102));
        department.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        department.setForeground(new java.awt.Color(255, 255, 255));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        jPanel5.add(department);
        department.setBounds(1590, 180, 280, 60);

        jLabel6.setFont(new java.awt.Font("FZYaoTi", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMPLOYEE MANAGEMENT");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(20, 10, 660, 110);

        locality.setBackground(new java.awt.Color(0, 102, 102));
        locality.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        locality.setForeground(new java.awt.Color(255, 255, 255));
        locality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localityActionPerformed(evt);
            }
        });
        jPanel5.add(locality);
        locality.setBounds(1590, 510, 280, 60);

        state.setBackground(new java.awt.Color(0, 102, 102));
        state.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        state.setForeground(new java.awt.Color(255, 255, 255));
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        jPanel5.add(state);
        state.setBounds(1590, 670, 280, 60);

        city.setBackground(new java.awt.Color(0, 102, 102));
        city.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel5.add(city);
        city.setBounds(1590, 590, 280, 60);

        post.setBackground(new java.awt.Color(0, 102, 102));
        post.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        post.setForeground(new java.awt.Color(255, 255, 255));
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        jPanel5.add(post);
        post.setBounds(1590, 260, 280, 60);

        salary.setBackground(new java.awt.Color(0, 102, 102));
        salary.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        salary.setForeground(new java.awt.Color(255, 255, 255));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel5.add(salary);
        salary.setBounds(1630, 340, 240, 60);

        degree.setBackground(new java.awt.Color(0, 102, 102));
        degree.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        degree.setForeground(new java.awt.Color(255, 255, 255));
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });
        jPanel5.add(degree);
        degree.setBounds(990, 750, 280, 60);

        jLabel27.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("D.O.B");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(760, 350, 120, 50);

        jLabel31.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Mobile No.");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(760, 520, 220, 40);

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.add(jButton9);
        jButton9.setBounds(760, 120, 990, 9);

        jLabel29.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Email-ID");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(760, 590, 170, 60);

        jLabel28.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Aadhar no.");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(760, 670, 210, 60);

        jLabel30.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("Employee ID");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(750, 180, 230, 60);

        jLabel32.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("Search Employee");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(810, 40, 330, 60);

        mobile.setBackground(new java.awt.Color(0, 102, 102));
        mobile.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        mobile.setForeground(new java.awt.Color(255, 255, 255));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel5.add(mobile);
        mobile.setBounds(1040, 510, 230, 60);

        email.setBackground(new java.awt.Color(0, 102, 102));
        email.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel5.add(email);
        email.setBounds(990, 590, 280, 60);

        aadhar.setBackground(new java.awt.Color(0, 102, 102));
        aadhar.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        aadhar.setForeground(new java.awt.Color(255, 255, 255));
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        jPanel5.add(aadhar);
        aadhar.setBounds(990, 670, 280, 60);

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("FZYaoTi", 0, 30)); // NOI18N
        female.setForeground(new java.awt.Color(0, 102, 102));
        female.setText("Female");
        jPanel5.add(female);
        female.setBounds(1130, 430, 140, 60);

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("FZYaoTi", 0, 30)); // NOI18N
        male.setForeground(new java.awt.Color(0, 102, 102));
        male.setText("Male");
        jPanel5.add(male);
        male.setBounds(990, 430, 140, 60);

        jLabel33.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("Name");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(760, 250, 110, 70);

        jLabel34.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("Locality");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(1370, 510, 160, 50);

        name.setBackground(new java.awt.Color(0, 102, 102));
        name.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel5.add(name);
        name.setBounds(990, 260, 280, 60);

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel5.add(id);
        id.setBounds(990, 180, 280, 60);

        jLabel7.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("+91");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(980, 500, 54, 80);

        join.setBackground(new java.awt.Color(0, 102, 102));
        join.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        join.setForeground(new java.awt.Color(255, 255, 255));
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        jPanel5.add(join);
        join.setBounds(1590, 420, 280, 60);

        dob.setBackground(new java.awt.Color(0, 102, 102));
        dob.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel5.add(dob);
        dob.setBounds(990, 340, 280, 60);

        employee.setBackground(new java.awt.Color(0, 102, 102));
        employee.setFont(new java.awt.Font("FZYaoTi", 0, 35)); // NOI18N
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel5.add(employee);
        employee.setBounds(1200, 40, 470, 60);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(40, 120, 620, 9);

        jLabel4.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Rs.");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(1580, 330, 47, 80);

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-client-48.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13);
        jButton13.setBounds(1750, 40, 80, 60);

        jButton1.setBackground(new java.awt.Color(200, 200, 200));
        jButton1.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("LEAVE MANAGEMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(80, 390, 560, 80);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setText("REMOVE EMPLOYEE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(80, 650, 560, 80);

        jButton6.setBackground(new java.awt.Color(200, 200, 200));
        jButton6.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("PAY ROLL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(80, 520, 560, 80);

        jLabel36.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 102));
        jLabel36.setText("Join-date");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(1370, 420, 210, 60);

        jButton7.setBackground(new java.awt.Color(200, 200, 200));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(90, 850, 560, 110);

        jButton10.setBackground(new java.awt.Color(0, 153, 153));
        jButton10.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("MODIFY EMPLOYEE DETAILS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(80, 260, 560, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halfblue.jpg"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(-100, 0, 820, 1000);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(730, 950, 570, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(800, 910, 380, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel5.add(jLabel1);
        jLabel1.setBounds(720, 0, 1240, 1000);

        user.setText("jLabel9");
        jPanel5.add(user);
        user.setBounds(10, 20, 41, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel5.add(jLabel3);
        jLabel3.setBounds(720, 0, 1240, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        PreparedStatement mystmt=null;
        try{
           
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
             String sq = "Select * from employee where Employee_id=?";           
            PreparedStatement pst = con.prepareStatement(sq);
            pst.setString(1, employee.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
              int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
           
          
           String sql = "Select * from employee where Employee_id=?";           
           pst = con.prepareStatement(sql);
            pst.setString(1, employee.getText());
            rs = pst.executeQuery();
            
                String quer="UPDATE employee SET Employee_id=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(quer);
                mystmt.setString(1, id.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                 String r="UPDATE employee SET Date_of_birth=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(r);
                mystmt.setString(1, dob.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                 String q="UPDATE employee SET Joiningdate=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(q);
                mystmt.setString(1, join.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                
              String que="UPDATE employee SET Employee_name=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(que);
                mystmt.setString(1, name.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                
                  String str=mobile.getText();
                    if(str.length()==10){
               String qu="UPDATE employee SET Mobile=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(qu);
                mystmt.setString(1, mobile.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                    }
                    else{
                      JOptionPane.showMessageDialog(this,"Enter valid Mobile no.","INVALID",JOptionPane.WARNING_MESSAGE);
                      mobile.setText("");
                    }
                
                 String G="UPDATE employee SET Email_ID=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(G);
                mystmt.setString(1, email.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                String a="UPDATE employee SET Qualification=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(a);
                mystmt.setString(1, degree.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
               String b="UPDATE employee SET Salary=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(b);
                mystmt.setString(1, salary.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
               String c="UPDATE employee SET Locality=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(c);
                mystmt.setString(1, locality.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                String d="UPDATE employee SET City=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(d);
                mystmt.setString(1, city.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                String e="UPDATE employee SET State=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(e);
                mystmt.setString(1, state.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                                           
                       
                
                String g="UPDATE employee SET Department=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(g);
                mystmt.setString(1, department.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                String h="UPDATE employee SET Aadhar_no=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(h);
                mystmt.setString(1, aadhar.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                String i="UPDATE employee SET Job=? WHERE Employee_id=?";
                mystmt= con.prepareStatement(i);
                mystmt.setString(1, post.getText());
                mystmt.setString(2, employee.getText());
                mystmt.executeUpdate();
                
                       if(male.isSelected()){
                     String m="Male";   
                      String s="UPDATE employee SET Gender=? WHERE Employee_id=?";
                       mystmt= con.prepareStatement(s);
                       mystmt.setString(1, m);
                       mystmt.setString(2, employee.getText());
                       mystmt.executeUpdate();
                    }
                     if(female.isSelected()){
                     String m="Female";       
                       String x="UPDATE employee SET Gender=? WHERE Employee_id=?";
                       mystmt= con.prepareStatement(x);
                       mystmt.setString(1, m);
                       mystmt.setString(2, employee.getText());
                       mystmt.executeUpdate();
                    }
                     
                        
                       

                JOptionPane.showMessageDialog(this,"Employee details updated","Successful",JOptionPane.INFORMATION_MESSAGE);
                id.setText("");
               
                dob.setText("");
                join.setText(""); 
                dob.setText("");
                   mobile.setText("");
                    email.setText("");
                     degree.setText("");
                      salary.setText("");
                       locality.setText("");
                        city.setText("");
                         state.setText("");
                         join.setText("");
                         name.setText("");
                           department.setText("");
                           aadhar.setText("");
                post.setText("");
             
        }
       
        }
            else{
             JOptionPane.showMessageDialog(this,"INVALID Employee ID","Unknown",JOptionPane.INFORMATION_MESSAGE);
            }
        }
            
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
             JOptionPane.showMessageDialog(this,"Employee details Cannot be updated please check, Entered data","Failed",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String us = user.getText();
        new LEAVEMANAGEMENT(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String us = user.getText();
        new PAYROLL(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new ADMINHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void localityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localityActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         PreparedStatement mystmt=null;
         ResultSet rs=null;
        try{
           
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");   
        mystmt = con.prepareStatement( "Select * from employee where Employee_id=?");
            mystmt.setString(1, employee.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                id.setText(rs.getString("Employee_id"));
             
                 name.setText(rs.getString("Employee_name"));
                   mobile.setText(rs.getString("Mobile"));
                    email.setText(rs.getString("Email_ID"));
                     degree.setText(rs.getString("Qualification"));
                      salary.setText(rs.getString("Salary")); 
                       locality.setText(rs.getString("Locality"));
                        city.setText(rs.getString("City"));
                         state.setText(rs.getString("State"));
                      dob.setText(rs.getString("Date_of_birth"));
                        join.setText(rs.getString("Joiningdate"));
                                                
                        department.setText(rs.getString("Department"));
                           aadhar.setText(rs.getString("Aadhar_no"));
                post.setText(rs.getString("Job"));
                 
                
            }
            else{
              JOptionPane.showMessageDialog(this,"No Results"+ "","Anticipated",JOptionPane.INFORMATION_MESSAGE);
            
            
            }
        }
                   catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
                      
    }//GEN-LAST:event_jButton13ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLOYEEMANAGEMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private javax.swing.JTextField degree;
    private javax.swing.JTextField department;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField employee;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField join;
    private javax.swing.JTextField locality;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField post;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField state;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
