

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class EMPLOYEEHOME extends javax.swing.JFrame {

    /**
     * Creates new form EMPLOYEEHOME
     */
    public EMPLOYEEHOME() {
        initComponents();
    }
    
     public EMPLOYEEHOME(String us){
         initComponents();
         user.setText(us);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        admin = new javax.swing.JButton();
        admin3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        admin8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        admin11 = new javax.swing.JButton();
        admin9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        admin5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        admin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        admin.setBackground(new java.awt.Color(0, 102, 102));
        admin.setForeground(new java.awt.Color(0, 102, 102));
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bill-100.png"))); // NOI18N
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel2.add(admin);
        admin.setBounds(680, 230, 190, 180);

        admin3.setBackground(new java.awt.Color(0, 102, 102));
        admin3.setForeground(new java.awt.Color(0, 102, 102));
        admin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-planner-100.png"))); // NOI18N
        admin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin3ActionPerformed(evt);
            }
        });
        jPanel2.add(admin3);
        admin3.setBounds(1060, 230, 190, 180);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("WHOLE SALE BILLLING");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(660, 410, 240, 50);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("SETTINGS");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(1280, 740, 160, 50);

        admin8.setBackground(new java.awt.Color(0, 102, 102));
        admin8.setForeground(new java.awt.Color(0, 102, 102));
        admin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-admin-settings-male-100.png"))); // NOI18N
        admin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin8ActionPerformed(evt);
            }
        });
        jPanel2.add(admin8);
        admin8.setBounds(1250, 560, 190, 180);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("BILLED INFO");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(910, 740, 130, 50);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("MEETING INFORMATION");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(1410, 410, 280, 50);

        admin11.setBackground(new java.awt.Color(0, 102, 102));
        admin11.setForeground(new java.awt.Color(0, 102, 102));
        admin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-in-inventory-100 (1).png"))); // NOI18N
        admin11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin11ActionPerformed(evt);
            }
        });
        jPanel2.add(admin11);
        admin11.setBounds(880, 560, 190, 180);

        admin9.setBackground(new java.awt.Color(0, 102, 102));
        admin9.setForeground(new java.awt.Color(0, 102, 102));
        admin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-100 (1).png"))); // NOI18N
        admin9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin9ActionPerformed(evt);
            }
        });
        jPanel2.add(admin9);
        admin9.setBounds(1430, 230, 190, 180);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("WORK SHIFT");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(1090, 410, 140, 50);

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setFont(new java.awt.Font("FZYaoTi", 0, 75)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(user);
        user.setBounds(900, 20, 810, 100);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("PRODUCTS INFO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(510, 740, 180, 50);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("FZYaoTi", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("RETAIL BILLING");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(320, 410, 160, 50);

        admin5.setBackground(new java.awt.Color(0, 102, 102));
        admin5.setForeground(new java.awt.Color(0, 102, 102));
        admin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-multiple-devices-100.png"))); // NOI18N
        admin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin5ActionPerformed(evt);
            }
        });
        jPanel2.add(admin5);
        admin5.setBounds(500, 560, 190, 180);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("FZYaoTi", 0, 75)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WELCOME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 20, 370, 100);

        admin1.setBackground(new java.awt.Color(0, 102, 102));
        admin1.setForeground(new java.awt.Color(0, 102, 102));
        admin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bill-100 (1).png"))); // NOI18N
        admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin1ActionPerformed(evt);
            }
        });
        jPanel2.add(admin1);
        admin1.setBounds(310, 230, 190, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 150, 1700, 750);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1930, 1030);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed

    }//GEN-LAST:event_adminActionPerformed

    private void admin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin3ActionPerformed

    private void admin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin5ActionPerformed
       String us=user.getText();
       new EMPLOYEEDEVICES(us).setVisible(true);
      dispose();   
    }//GEN-LAST:event_admin5ActionPerformed

    private void admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin1ActionPerformed
       String us=user.getText();
       new RETAILBILL(us).setVisible(true);
      dispose(); 
    }//GEN-LAST:event_admin1ActionPerformed

    private void admin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin8ActionPerformed
        String us=user.getText();
       new EMPLOYEESETTINGS(us).setVisible(true);
      dispose(); 
    }//GEN-LAST:event_admin8ActionPerformed

    private void admin9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin9ActionPerformed
        String us=user.getText();
     new EMPLOYEESCHEDULE(us).setVisible(true);
     dispose();
    }//GEN-LAST:event_admin9ActionPerformed

    private void admin11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEEHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLOYEEHOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton admin1;
    private javax.swing.JButton admin11;
    private javax.swing.JButton admin3;
    private javax.swing.JButton admin5;
    private javax.swing.JButton admin8;
    private javax.swing.JButton admin9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
