/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author josep
 */
public class EMPLOYEESCHEDULE extends javax.swing.JFrame {

    /**
     * Creates new form EMPLOYEESCHEDULE
     */
    public EMPLOYEESCHEDULE() {
        initComponents();
    }
     public EMPLOYEESCHEDULE(String us){
         initComponents();
         user.setText(us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schedule = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 170, 1740, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 950, 570, 40);

        schedule.setBackground(new java.awt.Color(0, 102, 102));
        schedule.setFont(new java.awt.Font("FZYaoTi", 0, 45)); // NOI18N
        schedule.setForeground(new java.awt.Color(255, 255, 255));
        schedule.setText("GET INFO");
        schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleActionPerformed(evt);
            }
        });
        jPanel1.add(schedule);
        schedule.setBounds(1430, 820, 230, 110);

        jLabel15.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("MEETING ID :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(600, 270, 240, 60);

        jLabel8.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("DATE : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 340, 240, 100);

        time.setBackground(new java.awt.Color(0, 102, 102));
        time.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        time.setForeground(new java.awt.Color(255, 102, 102));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
        });
        jPanel1.add(time);
        time.setBounds(920, 450, 210, 50);

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        id.setForeground(new java.awt.Color(255, 102, 102));
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(920, 280, 210, 50);

        date.setBackground(new java.awt.Color(0, 102, 102));
        date.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        date.setForeground(new java.awt.Color(255, 102, 102));
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(920, 370, 200, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-planner-100.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1180, 50, 120, 100);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-go-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(460, 810, 150, 120);

        jLabel14.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("TIME :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(600, 446, 240, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(740, 910, 380, 40);

        des.setColumns(20);
        des.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        des.setForeground(new java.awt.Color(255, 102, 102));
        des.setRows(5);
        jScrollPane1.setViewportView(des);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(910, 560, 330, 260);

        jLabel13.setFont(new java.awt.Font("FZYaoTi", 0, 80)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MEETING INFO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(600, 40, 540, 120);

        jLabel12.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("DESCRIPTION :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(600, 550, 320, 46);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1920, 240);
        jPanel1.add(user);
        user.setBounds(1620, 180, 70, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 240, 1920, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked

    }//GEN-LAST:event_dateMouseClicked

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timeMouseClicked

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new EMPLOYEEHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
        PreparedStatement mystmt=null;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");

            String sql = "Select * from schedule where Created_by=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "john52");
            ResultSet rs=pst.executeQuery();

            if(rs.next()){
                id.setText(rs.getString("ID"));
                date.setText(rs.getString("Date"));
                time.setText(rs.getString("Time"));
                des.setText(rs.getString("Description"));

            }

            else{
                JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);
                this.setVisible(false);
                String us=user.getText();
                new ADMINHOME(us).setVisible(true);
                dispose();
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_scheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEESCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLOYEESCHEDULE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTextArea des;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton schedule;
    private javax.swing.JLabel time;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
