
import java.sql.*; 
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class PAYROLL extends javax.swing.JFrame {

    /**
     * Creates new form PAYROLL
     */
    public PAYROLL() {
        initComponents();
    }
    
      String from,to,host,sub,content;
     public PAYROLL(String us){
         initComponents();
         user.setText(us);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salary1 = new javax.swing.JLabel();
        join = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        credit = new javax.swing.JButton();
        qualification = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        job = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        time1 = new javax.swing.JTextField();
        tomail = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(760, 950, 570, 40);

        salary1.setBackground(new java.awt.Color(0, 102, 102));
        salary1.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        salary1.setForeground(new java.awt.Color(0, 102, 102));
        salary1.setText("Rs.");
        salary1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salary1MouseClicked(evt);
            }
        });
        jPanel1.add(salary1);
        salary1.setBounds(1570, 420, 50, 60);

        join.setBackground(new java.awt.Color(0, 102, 102));
        join.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        join.setForeground(new java.awt.Color(0, 204, 153));
        join.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinMouseClicked(evt);
            }
        });
        jPanel1.add(join);
        join.setBounds(1660, 540, 260, 50);

        salary.setBackground(new java.awt.Color(0, 102, 102));
        salary.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        salary.setForeground(new java.awt.Color(0, 204, 153));
        salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryMouseClicked(evt);
            }
        });
        jPanel1.add(salary);
        salary.setBounds(1630, 420, 290, 60);

        credit.setBackground(new java.awt.Color(0, 102, 102));
        credit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-credit-card-interest-100.png"))); // NOI18N
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        jPanel1.add(credit);
        credit.setBounds(1370, 810, 140, 130);

        qualification.setBackground(new java.awt.Color(0, 102, 102));
        qualification.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        qualification.setForeground(new java.awt.Color(0, 204, 153));
        qualification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qualificationMouseClicked(evt);
            }
        });
        jPanel1.add(qualification);
        qualification.setBounds(1650, 300, 260, 50);

        jLabel8.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("JOB POST :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(780, 420, 240, 50);

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(1200, 40, 280, 50);

        name.setBackground(new java.awt.Color(0, 102, 102));
        name.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(0, 204, 153));
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(1090, 300, 270, 50);

        department.setBackground(new java.awt.Color(0, 102, 102));
        department.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        department.setForeground(new java.awt.Color(0, 204, 153));
        department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentMouseClicked(evt);
            }
        });
        jPanel1.add(department);
        department.setBounds(1070, 540, 290, 50);

        job.setBackground(new java.awt.Color(0, 102, 102));
        job.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        job.setForeground(new java.awt.Color(0, 204, 153));
        job.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobMouseClicked(evt);
            }
        });
        jPanel1.add(job);
        job.setBounds(1080, 420, 270, 50);

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-client-48.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(1520, 40, 70, 50);

        jLabel18.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("SALARY (MONTH) :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(990, 650, 320, 40);

        month.setFont(new java.awt.Font("FZYaoTi", 1, 30)); // NOI18N
        month.setModel(new javax.swing.SpinnerListModel(new String[] {"JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"}));
        jPanel1.add(month);
        month.setBounds(1330, 650, 260, 50);

        jLabel10.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("DEPARTMENT :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(780, 540, 250, 40);

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 102));
        jButton10.setText("MODIFY EMPLOYEE DETAILS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(80, 260, 560, 80);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setText("REMOVE EMPLOYEE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(80, 650, 560, 80);

        jLabel20.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("SALARY :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1370, 410, 180, 70);

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jButton9);
        jButton9.setBounds(810, 120, 1080, 9);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-show-property-100.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1680, 810, 140, 130);

        jButton1.setBackground(new java.awt.Color(200, 200, 200));
        jButton1.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("LEAVE MANAGEMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 390, 560, 80);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(40, 120, 680, 9);

        jLabel17.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("EMPLOYEE ID :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(920, 30, 270, 60);

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("PAY ROLL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(80, 520, 560, 80);

        jLabel21.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("JOINING DATE :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1370, 530, 290, 60);

        jLabel19.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("QUALIFICATION :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1370, 290, 310, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(830, 920, 380, 40);

        jLabel13.setFont(new java.awt.Font("FZYaoTi", 0, 80)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PAYROLL");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(220, 10, 370, 120);

        jLabel12.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("EMPLOYEE NAME :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(780, 300, 320, 46);

        jButton7.setBackground(new java.awt.Color(200, 200, 200));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(90, 850, 560, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(760, 0, 1160, 1020);
        jPanel1.add(user);
        user.setBounds(1876, 142, 30, 20);

        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        jPanel1.add(time1);
        time1.setBounds(1490, 320, 6, 22);
        jPanel1.add(tomail);
        tomail.setBounds(1460, 260, 0, 10);
        jPanel1.add(tim);
        tim.setBounds(1510, 810, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halfblue.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-100, 0, 860, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        if(id==null){
            credit.setEnabled(false);
        }
        else{
            credit.setEnabled(true);
        }
    }//GEN-LAST:event_idKeyTyped

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked

    private void jobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobMouseClicked

    }//GEN-LAST:event_jobMouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from employee where Employee_id=?");
            mystmt.setString(1, id.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                id.setText(rs.getString("Employee_id"));
                name.setText(rs.getString("Employee_name"));
                job.setText(rs.getString("Job"));
                department.setText(rs.getString("Department"));
                salary.setText(rs.getString("Salary"));
                qualification.setText(rs.getString("Qualification"));
                join.setText(rs.getString("Joiningdate"));
            }
            else{
                JOptionPane.showMessageDialog(this,"No Employee Record Found!!!"+ "","Anticipated",JOptionPane.INFORMATION_MESSAGE);
                id.setText("");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed

    }//GEN-LAST:event_time1ActionPerformed

    private void departmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentMouseClicked

    private void qualificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualificationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationMouseClicked

    private void salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryMouseClicked

    private void joinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_joinMouseClicked

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        PreparedStatement mystmt=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
            String sq = "Select * from employee where Employee_id=?";
            PreparedStatement pst = con.prepareStatement(sq);
            pst.setString(1, id.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){

                int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to credit salary?","Update Record",JOptionPane.YES_NO_OPTION);
                if(p==0){
                    tomail.setText(rs.getString("Email_ID"));
                    String q="insert into payroll(Employee_id, Credited_date, Credited_time, For_month )values(?,?,?,?)";
                    mystmt = con.prepareStatement(q);
                    mystmt.setString(1, id.getText());

                     SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                     java.util.Date date=new java.util.Date();
                     String a=(sdf.format(date));
                       mystmt.setString(2, a);
                  
                     SimpleDateFormat sd=new SimpleDateFormat("hh:mm:ss");
                     String b=sd.format(date);
                     mystmt.setString(3, b);
                     
                     tim.setText(month.getValue().toString());
                    mystmt.setString(4, tim.getText());
                    mystmt.executeUpdate();

                    
                   
                   
               String sql = "Select * from employee where Employee_id=?";
                    pst = con.prepareStatement(sql);
                    pst.setString(1, id.getText());
                    rs = pst.executeQuery();

                    if(rs.next()){
                        from = "hitachicompany452@gmail.com";
                        to = tomail.getText();
                        host = "localhost";
                        sub = "SALARY CREDITED";
                        content = "Dear "+name.getText()+", your Salary of, Rs."+salary.getText()+" has been Credited to your bank account on "+sdf.format(date)+", for the month of"+tim.getText()+" \n\n\n\nTHANK YOU \n\n\nREGARDS HITACHI VANTARA\nPRIVATE LIMITED";
                        Properties po= new Properties();
                        po.put("mail.smtp.auth","true");
                        po.put("mail.smtp.starttls.enable","true");
                        po.put("mail.smtp.host","smtp.gmail.com");
                        po.put("mail.smtp.port","587");
                        Session s= Session.getDefaultInstance(po, new javax.mail.Authenticator(){
                            protected PasswordAuthentication getPasswordAuthentication()
                            {
                                return new PasswordAuthentication("hitachicompany452@gmail.com","a.s.j.l.r");
                            }
                        });
                        try{
                            MimeMessage m = new MimeMessage(s);
                            m.setFrom(from);
                            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                            m.setText(content);
                            Transport.send(m);
                        }
                        catch(Exception e){
                            e.printStackTrace();
                        }

                        JOptionPane.showMessageDialog(this,"Salary has been Credited to "+name.getText()+"","Successful",JOptionPane.INFORMATION_MESSAGE);
                        id.setText("");
                        name.setText("");
                        job.setText("");
                        department.setText("");
                        salary.setText("");
                        qualification.setText("");
                        
                    }

                }

                else{
                    JOptionPane.showMessageDialog(this,"Unable to Credit salary, please try again later ("+name.getText()+") ","Failed",JOptionPane.WARNING_MESSAGE);
                    String us=user.getText();
                    new ADMINHOME(us).setVisible(true);
                    dispose();
                }
            }
             else{
                    JOptionPane.showMessageDialog(this,"INVALID Employee ID ","Failed",JOptionPane.WARNING_MESSAGE);
                    id.setText("");
            }
            

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_creditActionPerformed

    private void salary1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salary1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salary1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
           String us = user.getText();
        new EMPLOYEEMANAGEMENT(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String us = user.getText();
        new LEAVEMANAGEMENT(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String us = user.getText();
        new PAYROLL(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new ADMINHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String us = user.getText();
    new PAYROLLDATA(us).setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAYROLL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAYROLL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAYROLL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAYROLL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAYROLL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton credit;
    private javax.swing.JLabel department;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel job;
    private javax.swing.JLabel join;
    private javax.swing.JSpinner month;
    private javax.swing.JLabel name;
    private javax.swing.JLabel qualification;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel salary1;
    private javax.swing.JLabel tim;
    private javax.swing.JTextField time1;
    private javax.swing.JLabel tomail;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
