
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class SCHEDULE extends javax.swing.JFrame {

    /**
     * Creates new form SCHEDULE
     */
    public SCHEDULE() {
        initComponents();
       
    }

     public SCHEDULE(String us){
         initComponents();
         user.setText(us);
           SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        datee.getDayChooser().setMinSelectableDate(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schedule = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        time = new cambodia.raven.Time();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        datee = new com.toedter.calendar.JCalendar();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        time1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        notext = new javax.swing.JTextField();
        idd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 170, 1740, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 950, 570, 40);

        schedule.setBackground(new java.awt.Color(0, 102, 102));
        schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-64.png"))); // NOI18N
        schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleActionPerformed(evt);
            }
        });
        jPanel1.add(schedule);
        schedule.setBounds(1790, 880, 100, 90);

        jLabel15.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("MEETING ID :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(320, 320, 290, 70);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setForeground(new java.awt.Color(0, 102, 102));
        time.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        time.setMaximumSize(new java.awt.Dimension(222, 80));
        time.setMinimumSize(new java.awt.Dimension(222, 80));
        time.setPreferredSize(new java.awt.Dimension(222, 80));
        time.setTextRefernce(time1);
        jPanel1.add(time);
        time.setBounds(1160, 330, 150, 80);

        jLabel8.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("DATE : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1000, 500, 130, 70);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-bin-65.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 820, 100, 90);

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        id.setForeground(new java.awt.Color(0, 102, 102));
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(620, 330, 220, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-planner-100.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1310, 40, 120, 100);

        jLabel14.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("TIME :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1000, 340, 120, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(740, 910, 380, 40);

        des.setBackground(new java.awt.Color(0, 102, 102));
        des.setColumns(20);
        des.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        des.setForeground(new java.awt.Color(255, 255, 255));
        des.setRows(5);
        jScrollPane1.setViewportView(des);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(620, 510, 350, 260);

        jLabel13.setFont(new java.awt.Font("FZYaoTi", 0, 80)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SCHEDULE MEETING");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(600, 40, 680, 120);

        datee.setFont(new java.awt.Font("FZYaoTi", 0, 15)); // NOI18N
        jPanel1.add(datee);
        datee.setBounds(1150, 510, 490, 250);

        jLabel12.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("ABOUT MEETING :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 510, 310, 46);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-go-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(40, 850, 130, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 240, 1920, 760);
        jPanel1.add(user);
        user.setBounds(1486, 430, 70, 22);

        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        jPanel1.add(time1);
        time1.setBounds(1490, 320, 6, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1920, 240);

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d);
        d.setBounds(1416, 360, 100, 22);

        h.setText("0");
        jPanel1.add(h);
        h.setBounds(1530, 560, 13, 22);
        jPanel1.add(notext);
        notext.setBounds(1510, 350, 6, 22);

        idd.setText("MEET1003");
        jPanel1.add(idd);
        idd.setBounds(1510, 120, 66, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
     PreparedStatement mystmt=null;
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");     
            
              String sql = "Select * from schedule where Created_by=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, user.getText());
            ResultSet rs=pst.executeQuery();
            
            if(rs.next()){
             id.setText(rs.getString("ID"));
             int app=Integer.parseInt(id.getText());
            
            if(app==0){
                 int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
                  if(p==0){
                      
                id.setText("MEET1003");
             String G="UPDATE schedule SET ID=? WHERE Created_by=?";
                mystmt= con.prepareStatement(G);
                mystmt.setString(1, idd.getText());
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();
                
                 String j="UPDATE schedule SET Time=? WHERE Created_by=?";
                mystmt= con.prepareStatement(j);
                mystmt.setString(1, time1.getText());
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();
          
                
                 String a="UPDATE schedule SET Description=? WHERE Created_by=?";
                mystmt= con.prepareStatement(a);
                mystmt.setString(1, des.getText());
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date=sdf.format(datee.getDate());
                String h="UPDATE schedule SET Date=? WHERE Created_by=?";
                mystmt= con.prepareStatement(h);
                mystmt.setString(1, date);
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();
                 JOptionPane.showMessageDialog(this,"Meeting Scheduled on "+date+" ","Successfull",JOptionPane.WARNING_MESSAGE);
          
                String us=user.getText();
                 new ADMINHOME(us).setVisible(true);
                 dispose();
                  }
            }
            else{
             JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);
             this.setVisible(false);
             String us=user.getText();
             new ADMINHOME(us).setVisible(true);
             dispose();
            }
            }
        }
        catch(Exception e){
              JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);
            
             
        }
    }//GEN-LAST:event_scheduleActionPerformed

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        
    }//GEN-LAST:event_idMouseClicked

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
    time.showPopup();
    }//GEN-LAST:event_time1ActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
      
        
    }//GEN-LAST:event_dActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      PreparedStatement mystmt=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "Select * from schedule where Created_by=?";
           
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, user.getText());
            ResultSet rs = pst.executeQuery();
            String us=user.getText();

            if(rs.next()){
          
                 int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete old schedule?","Update Record",JOptionPane.YES_NO_OPTION);
                  if(p==0){

             String G="UPDATE schedule SET ID=? WHERE Created_by=?";
                mystmt= con.prepareStatement(G);
                mystmt.setString(1, h.getText());
                mystmt.setString(2, user.getText());
                mystmt.executeUpdate();       
                
               
                
                 JOptionPane.showMessageDialog(this,"Meeting Record deleted  ","Successfull",JOptionPane.WARNING_MESSAGE); 
                 des.setText("");
                 id.setText("");
                  }
            
           

            }
            else{
                JOptionPane.showMessageDialog(this,"Specified Credentials is INVALID","Anticipated",JOptionPane.ERROR_MESSAGE);
                des.setText("");
                id.setText("");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new ADMINHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCHEDULE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCHEDULE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private com.toedter.calendar.JCalendar datee;
    private javax.swing.JTextArea des;
    private javax.swing.JTextField h;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField notext;
    private javax.swing.JButton schedule;
    private cambodia.raven.Time time;
    private javax.swing.JTextField time1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
