/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*; 
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author josep
 */
public class WORKSHIFT extends javax.swing.JFrame {

    /**
     * Creates new form WORKSHIFT
     */
    public WORKSHIFT() {
        initComponents();
    }
    String from,to,host,sub,content;
     public WORKSHIFT(String us){
         initComponents();
         user.setText(us);
         schedule.setEnabled(false);
         schedule1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schedule = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        job = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        time = new javax.swing.JSpinner();
        schedule1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        time1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        tomail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 190, 1740, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Level 12, No 9/0, Lavelle Road, Bengaluru - 560051, India");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 950, 570, 40);

        schedule.setBackground(new java.awt.Color(0, 102, 102));
        schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-64.png"))); // NOI18N
        schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleActionPerformed(evt);
            }
        });
        jPanel1.add(schedule);
        schedule.setBounds(540, 820, 100, 90);

        jLabel8.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("JOB POST");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 500, 250, 40);

        id.setBackground(new java.awt.Color(0, 102, 102));
        id.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(960, 290, 280, 50);

        name.setBackground(new java.awt.Color(0, 102, 102));
        name.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        name.setForeground(new java.awt.Color(0, 102, 102));
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(960, 390, 280, 50);

        job.setBackground(new java.awt.Color(0, 102, 102));
        job.setFont(new java.awt.Font("FZYaoTi", 0, 36)); // NOI18N
        job.setForeground(new java.awt.Color(0, 102, 102));
        job.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobMouseClicked(evt);
            }
        });
        jPanel1.add(job);
        job.setBounds(960, 490, 280, 50);

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-client-48.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(1280, 290, 70, 50);

        jLabel10.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("SHIFT TIME");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 610, 250, 40);

        jLabel17.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("EMPLOYEE ID :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(600, 280, 270, 60);

        time.setFont(new java.awt.Font("FZYaoTi", 1, 40)); // NOI18N
        time.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel1.add(time);
        time.setBounds(960, 610, 80, 50);

        schedule1.setBackground(new java.awt.Color(0, 102, 102));
        schedule1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-64.png"))); // NOI18N
        schedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule1ActionPerformed(evt);
            }
        });
        jPanel1.add(schedule1);
        schedule1.setBounds(1317, 820, 100, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-100 (1).png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1260, 50, 120, 100);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Hitahi Vantara India Private Limited");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(740, 910, 380, 40);

        jLabel13.setFont(new java.awt.Font("FZYaoTi", 0, 80)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("WORK SHIFT");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(810, 40, 440, 120);

        combo.setFont(new java.awt.Font("FZYaoTi", 0, 30)); // NOI18N
        combo.setForeground(new java.awt.Color(0, 102, 102));
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(1040, 610, 80, 50);

        jLabel12.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("EMPLOYEE NAME :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(600, 390, 320, 46);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("FZYaoTi", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-go-back-100.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(110, 790, 130, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white2.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 240, 1920, 760);
        jPanel1.add(user);
        user.setBounds(1486, 430, 70, 22);

        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        jPanel1.add(time1);
        time1.setBounds(1490, 320, 6, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zzz.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1920, 240);
        jPanel1.add(tim);
        tim.setBounds(1530, 550, 0, 0);
        jPanel1.add(tomail);
        tomail.setBounds(1540, 320, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
        PreparedStatement mystmt=null;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
             String sq = "Select * from employee where Employee_id=?";           
            PreparedStatement pst = con.prepareStatement(sq);
            pst.setString(1, id.getText());
            ResultSet rs = pst.executeQuery();
             if(rs.next()){
           
         
                    int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to make new entry?","Update Record",JOptionPane.YES_NO_OPTION);
                    if(p==0){    
                         tomail.setText(rs.getString("Email_ID"));
                       String q="insert into workshift(Employee_id, Start_time, Meredies, Total_hrs)values(?,?,?,?)"; 
                       mystmt = con.prepareStatement(q);
                       mystmt.setString(1, id.getText());
                       
                       tim.setText(time.getValue().toString());
                       mystmt.setString(2, tim.getText());
                          
                       String meredies = combo.getSelectedItem().toString();
                        mystmt.setString(3, meredies);
                         mystmt.setString(4, "10");
                         mystmt.executeUpdate();
                         
            String sql = "Select * from workshift where Employee_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, id.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){   
                from = "hitachicompany452@gmail.com";
                to = tomail.getText();
                host = "localhost";
                sub = "UPDATED WORKSHIFT TIMING ";
                content = "Dear "+name.getText()+", ADMIN has Assigned Your WorkShift at "+tim.getText()+""+meredies+" kindly login accordingly\n\n\n\nTHANK YOU \n\n\nREGARDS HITACHI VANTARA\nPRIVATE LIMITED";
                Properties po= new Properties();
                po.put("mail.smtp.auth","true");
                po.put("mail.smtp.starttls.enable","true");
                po.put("mail.smtp.host","smtp.gmail.com");
                po.put("mail.smtp.port","587");
                Session s= Session.getDefaultInstance(po, new javax.mail.Authenticator(){
                    protected PasswordAuthentication getPasswordAuthentication()
                    {
                        return new PasswordAuthentication("hitachicompany452@gmail.com","a.s.j.l.r");
                    }
                });
                try{
                    MimeMessage m = new MimeMessage(s);
                    m.setFrom(from);
                    m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                    m.setText(content);
                    Transport.send(m);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                        

                         JOptionPane.showMessageDialog(this,"Work Shift has been Updated to "+tim.getText()+""+meredies+"!!! ","Successful",JOptionPane.INFORMATION_MESSAGE);
                        id.setText("");
                        name.setText("");
                        job.setText("");
                       }
                
                    }
                
                else{
                    JOptionPane.showMessageDialog(this,"Unable to Allote Shift ("+name.getText()+") ","Failed",JOptionPane.WARNING_MESSAGE);
                    String us=user.getText();
                    new ADMINHOME(us).setVisible(true);
                    dispose();
                }
             }else{
             JOptionPane.showMessageDialog(this,"Cannot Find Employee","Failed",JOptionPane.WARNING_MESSAGE);
             id.setText("");
             }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_scheduleActionPerformed

    private void jobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobMouseClicked

    }//GEN-LAST:event_jobMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String us = user.getText();
        new ADMINHOME(us).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
      
    }//GEN-LAST:event_time1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from employee where Employee_id=?");
            mystmt.setString(1, id.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                id.setText(rs.getString("Employee_id"));
                name.setText(rs.getString("Employee_name"));
                job.setText(rs.getString("Job"));

            }
            else{
                JOptionPane.showMessageDialog(this,"No Employee Record Found!!!"+ "","Anticipated",JOptionPane.INFORMATION_MESSAGE);
                id.setText("");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked

    private void schedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule1ActionPerformed

        PreparedStatement mystmt=null;
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hitachi?zeroDateTimeBehavior=convertToNull", "root", "");
             String sq = "Select * from employee where Employee_id=?";           
            PreparedStatement pst = con.prepareStatement(sq);
            pst.setString(1, id.getText());
            ResultSet rs = pst.executeQuery();
            
             if(rs.next()){
                    int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
                    if(p==0){
                         tomail.setText(rs.getString("Email_ID"));
                         String quer="UPDATE workshift SET Start_time=? WHERE Employee_id=?";
                         mystmt= con.prepareStatement(quer);
                           tim.setText(time.getValue().toString());
                         mystmt.setString(1, tim.getText());
                         mystmt.setString(2, id.getText());
                         mystmt.executeUpdate();
                         
                            String qu="UPDATE workshift SET Meredies=? WHERE Employee_id=?";
                         mystmt= con.prepareStatement(qu);
                          String meredies = combo.getSelectedItem().toString();
                        mystmt.setString(1, meredies);
                         mystmt.setString(2, id.getText());
                         mystmt.executeUpdate();
                         
                            String que="UPDATE workshift SET Total_hrs=? WHERE Employee_id=?";
                         mystmt= con.prepareStatement(que);
                         mystmt.setString(1, "10");
                         mystmt.setString(2, id.getText());
                         mystmt.executeUpdate();
                         
            String sql = "Select * from workshift where Employee_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, id.getText());
            rs = pst.executeQuery();
     
            if(rs.next()){   
                from = "hitachicompany452@gmail.com";
                to = tomail.getText();
                host = "localhost";
                sub = "UPDATED WORKSHIFT TIMING ";
                content = "Dear "+name.getText()+", ADMIN has Updated Your WorkShift To "+tim.getText()+""+meredies+" kindly login according to the Updated WorkShift\n\n\n\nTHANK YOU \n\n\nREGARDS HITACHI VANTARA\nPRIVATE LIMITED";
                Properties po= new Properties();
                po.put("mail.smtp.auth","true");
                po.put("mail.smtp.starttls.enable","true");
                po.put("mail.smtp.host","smtp.gmail.com");
                po.put("mail.smtp.port","587");
                Session s= Session.getDefaultInstance(po, new javax.mail.Authenticator(){
                    protected PasswordAuthentication getPasswordAuthentication()
                    {
                        return new PasswordAuthentication("hitachicompany452@gmail.com","a.s.j.l.r");
                    }
                });
                try{
                    MimeMessage m = new MimeMessage(s);
                    m.setFrom(from);
                    m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                    m.setText(content);
                    Transport.send(m);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                        

                         JOptionPane.showMessageDialog(this,"Work Shift has been Updated to "+tim.getText()+""+meredies+"!!! ","Successful",JOptionPane.INFORMATION_MESSAGE);
                        id.setText("");
                        name.setText("");
                        job.setText("");
                       }
        else{
        
        }
                        
                    }
                    else{
                    JOptionPane.showMessageDialog(this,"Unable to Allote Shift ("+name.getText()+") ","Failed",JOptionPane.WARNING_MESSAGE);
                    String us=user.getText();
                    new ADMINHOME(us).setVisible(true);
                    dispose();
                    }
                    
             }
                else{
                    JOptionPane.showMessageDialog(this,"Cannot Find Employee","Failed",JOptionPane.WARNING_MESSAGE);
                  id.setText("");      
             }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"There is an Existing Schedule ","Failed",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_schedule1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
       
    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
    if(id==null){
      schedule.setEnabled(false);
      schedule1.setEnabled(false);
    }
    else{
     schedule.setEnabled(true);
      schedule1.setEnabled(true);
    }
    }//GEN-LAST:event_idKeyTyped

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WORKSHIFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WORKSHIFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WORKSHIFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WORKSHIFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WORKSHIFT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel job;
    private javax.swing.JLabel name;
    private javax.swing.JButton schedule;
    private javax.swing.JButton schedule1;
    private javax.swing.JLabel tim;
    private javax.swing.JSpinner time;
    private javax.swing.JTextField time1;
    private javax.swing.JLabel tomail;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
